before_script:
  - composer install

test:
  script:
    - vendor/bin/phpunit --configuration=phpunit.xml.dist
  tags:
    - workflow-php-sdk
  except:
    - tags

code-sniffer:
  script:
    - vendor/bin/phpcs --standard=phpcs.ruleset.xml
  tags:
    - workflow-php-sdk
  except:
    - tags
