before_script:
  - sh ./bin/install-composer.sh
  - /usr/bin/php7.2 dist/composer.phar install --quiet --no-interaction --no-progress --optimize-autoloader --classmap-authoritative

test:
  script:
    - /usr/bin/php7.2 vendor/bin/phpunit --configuration=phpunit.xml.dist
  tags:
    - workflow-php-sdk
  except:
    - tags

code-sniffer:
  script:
    - /usr/bin/php7.2 vendor/bin/phpcs --standard=phpcs.ruleset.xml
  tags:
    - workflow-php-sdk
  except:
    - tags
